spring:
  profiles:
    active: xml-database

  jpa:
   # set it to true to show SQL statements
    show-sql: true
    database: mysql
    generate-ddl: true
    hibernate.ddl-auto: create-drop

  datasource: 
    url: jdbc:mysql://localhost:3306/pass
    username: root
    password:

server: 
  port: 8080
  
  session: 
    timeout: 30000